In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('secondary_data_no_miss.csv', sep = ';')

In [3]:
def hexcode_func(value):
    
    color = ''
    
# class
    if value == 'poisonous':
        color = '#3DF612'
    elif value == 'edible':
        color = '#ff99ff'
# cap shape
    elif value == 'convex':
        color = '#e76aa3'
    elif value == 'flat':
        color = '#e978ac'
    elif value == 'sunken':
        color = '#eb87b5'
    elif value == 'bell':
        color = '#ee96be'
    elif value == 'others':
        color = '#f0a5c7'
    elif value == 'spherical':
        color = '#f3b4d1'
    elif value == 'conical':
        color = '#f5c3da'
# cap surface
    elif value == 'sticky':
        color = '#065535'
    elif value == 'smooth':
        color = '#075f3c'
    elif value == 'scaly':
        color = '#08774b'
    elif value == 'shiny':
        color = '#0a8f5a'
    elif value == 'grooves':
        color = '#0ca769'
    elif value == 'd':
        color = '#0dbf78'
    elif value == 'fleshy':
        color = '#0fd787'
    elif value == 'silky':
        color = '#11ee96'
    elif value == 'fibrous':
        color = '#28f0a0'
    elif value == 'wrinkled':
        color = '#40f2ab'
    elif value == 'leathery':
        color = '#58f3b5'
# color, applies to multiple characteristics
    elif value == 'white':
        color = '#FFFFFF'
    elif value == 'brown':
        color = '#964B00'
    elif value == 'yellow':
        color = '#FFFF00'
    elif value == 'pink':
        color = '#FFC0CB'
    elif value == 'gray':
        color = '#808080'
    elif value == 'none':
        color = '#E9E9E9'
    elif value == 'orange':
        color = '#FFA500'
    elif value == 'black':
        color = '#000000'
    elif value == 'green':
        color = '#00FF00'
    elif value == 'red':
        color = '#FF0000'
    elif value == 'purple':
        color = '#800080'
    elif value == 'buff':
        color = '#F0DC82'
    elif value == 'blue':
        color = '#0000FF'
# true/false
    elif value == True:
        color = '#666666'
    elif value == False:
        color = '#e6e6e6'
# gill attachment
    elif value == 'adnate':
        color = '#fa525d'
    elif value == 'decurrent':
        color = '#fa626d'
    elif value == 'adnexed':
        color = '#fa6b74'
    elif value == 'pores':
        color = '#fb838b'
    elif value == 'free':
        color = '#fc9ca2'
    elif value == 'sinuate':
        color = '#fdb5ba'
# gill-spacing
    elif value == 'close':
        color = '#b34cf3'
    elif value == 'distant':
        color = '#CF8FF7'
# ring type
    elif value == 'evanescent':
        color = '#66c1e5'
    elif value == 'zone':
        color = '#7ccae9'
    elif value == 'flaring':
        color = '#87ceeb'
    elif value == 'large':
        color = '#92d3ed'
    elif value == 'grooved':
        color = '#a8dcf0'
    elif value == 'pendant':
        color = '#bee5f4'
    elif value == 'movable':
        color = '#d3edf8'
# habitat
    elif value == 'woods':
        color = '#f9d51f'
    elif value == 'grasses':
        color = '#fada38'
    elif value == 'leaves':
        color = '#fbde51'
    elif value == 'meadows':
        color = '#fbe36a'
    elif value == 'heaths':
        color = '#fce883'
    elif value == 'waste':
        color = '#fcea8b'
    elif value == 'paths':
        color = '#fcec9c'
    elif value == 'urban':
        color = '#fdf1b4'
# season
    elif value == 'autumn':
        color = '#ff9900'
    elif value == 'summer':
        color = '#84B674'
    elif value == 'winter':
        color = '#99ccff'
    elif value == 'spring':
        color = '#03FF7F'

    return color

In [4]:
data.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
0,e,1.26,x,g,y,f,d,c,w,5.04,1.73,y,f,f,d,a
1,e,10.32,f,e,b,f,a,c,b,4.68,19.44,w,t,f,d,a
2,p,0.92,x,g,p,f,a,c,p,4.59,1.15,k,f,f,d,u
3,p,4.27,x,t,p,f,x,c,w,4.55,6.52,w,f,f,d,a
4,e,3.08,f,s,w,f,d,d,w,2.67,5.18,w,f,f,m,a

In [5]:
# replace all letters with actual value

data = data.replace(
    {
    'class': {'p': 'poisonous', 'e': 'edible'},
    'cap-shape': {'b': 'bell', 'c': 'conical', 'x': 'convex', 'f': 'flat', 's': 'sunken', 'p': 'spherical', 'o': 'others'},
    'cap-surface': {'i': 'fibrous', 'g': 'grooves', 'y': 'scaly', 's': 'smooth', 'h': 'shiny', 'l': 'leathery', 'k': 'silky', 't': 'sticky', 'w': 'wrinkled', 'e': 'fleshy'},
    'cap-color': {'n': 'brown', 'b': 'buff', 'g': 'gray', 'r': 'green', 'p': 'pink', 'u': 'purple', 'e': 'red', 'w': 'white', 'y': 'yellow', 'l': 'blue', 'o': 'orange', 'k': 'black'},
    'gill-attachment': {'a': 'adnate', 'x': 'adnexed', 'd': 'decurrent', 'e': 'free', 's': 'sinuate', 'p': 'pores', 'f': 'none', '?': 'unknown'},
    'gill-spacing': {'c': 'close', 'd': 'distant', 'f': 'none'},
    'gill-color': {'n': 'brown', 'b': 'buff', 'g': 'gray', 'r': 'green', 'p': 'pink', 'u': 'purple', 'e': 'red', 'w': 'white', 'y': 'yellow', 'l': 'blue', 'o': 'orange', 'k': 'black', 'f': 'none'},
    'stem-color': {'n': 'brown', 'b': 'buff', 'g': 'gray', 'r': 'green', 'p': 'pink', 'u': 'purple', 'e': 'red', 'w': 'white', 'y': 'yellow', 'l': 'blue', 'o': 'orange', 'k': 'black', 'f': 'none'},
    'ring-type': {'c': 'cobwebby', 'e': 'evanescent', 'r': 'flaring', 'g': 'grooved', 'l': 'large', 'p': 'pendant', 's': 'sheathing', 'z': 'zone', 'y': 'scaly', 'm': 'movable', 'f': 'none', '?': 'unknown'},
    'habitat': {'g': 'grasses', 'l': 'leaves', 'm': 'meadows', 'p': 'paths', 'h': 'heaths', 'u': 'urban', 'w': 'waste', 'd': 'woods'},
    'season': {'s': 'spring', 'u': 'summer', 'a': 'autumn', 'w': 'winter'}
    })

# convert t/f columns to boolean.
data['does-bruise-or-bleed'] = data['does-bruise-or-bleed']=='t'
data['has-ring'] = data['has-ring']=='t'

In [6]:
data.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
0,edible,1.26,convex,grooves,yellow,False,decurrent,close,white,5.04,1.73,yellow,False,none,woods,autumn
1,edible,10.32,flat,fleshy,buff,False,adnate,close,buff,4.68,19.44,white,True,none,woods,autumn
2,poisonous,0.92,convex,grooves,pink,False,adnate,close,pink,4.59,1.15,black,False,none,woods,summer
3,poisonous,4.27,convex,sticky,pink,False,adnexed,close,white,4.55,6.52,white,False,none,woods,autumn
4,edible,3.08,flat,smooth,white,False,decurrent,distant,white,2.67,5.18,white,False,none,meadows,autumn

In [7]:
class_df = data['class'].value_counts()
class_df = pd.DataFrame(class_df)
class_df = class_df.rename(columns={'class': 'count'})
class_df = class_df.reset_index()
class_df = class_df.rename(columns={'index': 'value'})
class_df['color'] = class_df['value'].apply(lambda x: hexcode_func(x))
class_df.head()

       value  count    color
0  poisonous  33888  #3DF612
1     edible  27181  #ff99ff

In [8]:
cap_shape_df = data['cap-shape'].value_counts()
cap_shape_df = pd.DataFrame(cap_shape_df)
cap_shape_df = cap_shape_df.rename(columns={'cap-shape': 'count'})
cap_shape_df = cap_shape_df.reset_index()
cap_shape_df = cap_shape_df.rename(columns={'index': 'value'})
cap_shape_df['color'] = cap_shape_df['value'].apply(lambda x: hexcode_func(x))
cap_shape_df

       value  count    color
0     convex  26802  #e76aa3
1       flat  13492  #e978ac
2     sunken   7099  #eb87b5
3       bell   5697  #ee96be
4     others   3472  #f0a5c7
5  spherical   2685  #f3b4d1
6    conical   1822  #f5c3da

In [9]:
cap_surface_df = data['cap-surface'].value_counts()
cap_surface_df = pd.DataFrame(cap_surface_df)
cap_surface_df = cap_surface_df.rename(columns={'cap-surface': 'count'})
cap_surface_df = cap_surface_df.reset_index()
cap_surface_df = cap_surface_df.rename(columns={'index': 'value'})
cap_surface_df['color'] = cap_surface_df['value'].apply(lambda x: hexcode_func(x))
cap_surface_df

       value  count    color
0     sticky  22253  #065535
1     smooth   7577  #075f3c
2      scaly   6396  #08774b
3      shiny   5029  #0a8f5a
4    grooves   4740  #0ca769
5          d   4440  #0dbf78
6     fleshy   2590  #0fd787
7      silky   2283  #11ee96
8    fibrous   2198  #28f0a0
9   wrinkled   2151  #40f2ab
10  leathery   1412  #58f3b5

In [10]:
cap_color_df = data['cap-color'].value_counts()
cap_color_df = pd.DataFrame(cap_color_df)
cap_color_df = cap_color_df.rename(columns={'cap-color': 'count'})
cap_color_df = cap_color_df.reset_index()
cap_color_df = cap_color_df.rename(columns={'index': 'value'})
cap_color_df['color'] = cap_color_df['value'].apply(lambda x: hexcode_func(x))
cap_color_df

     value  count    color
0    brown  24438  #964B00
1   yellow   8487  #FFFF00
2    white   7592  #FFFFFF
3     gray   4363  #808080
4      red   4027  #FF0000
5   orange   3625  #FFA500
6    green   1804  #00FF00
7   purple   1783  #800080
8     pink   1652  #FFC0CB
9     buff   1258  #F0DC82
10   black   1223  #000000
11    blue    817  #0000FF

In [11]:
bruise_bleed_df = data['does-bruise-or-bleed'].value_counts()
bruise_bleed_df = pd.DataFrame(bruise_bleed_df)
bruise_bleed_df = bruise_bleed_df.rename(columns={'does-bruise-or-bleed': 'count'})
bruise_bleed_df = bruise_bleed_df.reset_index()
bruise_bleed_df = bruise_bleed_df.rename(columns={'index': 'value'})
bruise_bleed_df['color'] = bruise_bleed_df['value'].apply(lambda x: hexcode_func(x))
bruise_bleed_df

   value  count    color
0  False  50479  #e6e6e6
1   True  10590  #666666

In [12]:
gill_attachment_df = data['gill-attachment'].value_counts()
gill_attachment_df = pd.DataFrame(gill_attachment_df)
gill_attachment_df = gill_attachment_df.rename(columns={'gill-attachment': 'count'})
gill_attachment_df = gill_attachment_df.reset_index()
gill_attachment_df = gill_attachment_df.rename(columns={'index': 'value'})
gill_attachment_df['color'] = gill_attachment_df['value'].apply(lambda x: hexcode_func(x))
gill_attachment_df

       value  count    color
0     adnate  22560  #fa525d
1  decurrent  10269  #fa626d
2    adnexed   7413  #fa6b74
3      pores   6001  #fb838b
4    sinuate   5648  #fdb5ba
5       free   5648  #fc9ca2
6       none   3530  #E9E9E9

In [13]:
gill_spacing_df = data['gill-spacing'].value_counts()
gill_spacing_df = pd.DataFrame(gill_spacing_df)
gill_spacing_df = gill_spacing_df.rename(columns={'gill-spacing': 'count'})
gill_spacing_df = gill_spacing_df.reset_index()
gill_spacing_df = gill_spacing_df.rename(columns={'index': 'value'})
gill_spacing_df['color'] = gill_spacing_df['value'].apply(lambda x: hexcode_func(x))
gill_spacing_df

     value  count    color
0    close  49773  #b34cf3
1  distant   7766  #CF8FF7
2     none   3530  #E9E9E9

In [14]:
gill_color_df = data['gill-color'].value_counts()
gill_color_df = pd.DataFrame(gill_color_df)
gill_color_df = gill_color_df.rename(columns={'gill-color': 'count'})
gill_color_df = gill_color_df.reset_index()
gill_color_df = gill_color_df.rename(columns={'index': 'value'})
gill_color_df['color'] = gill_color_df['value'].apply(lambda x: hexcode_func(x))
gill_color_df

     value  count    color
0    white  18617  #FFFFFF
1    brown   9770  #964B00
2   yellow   9419  #FFFF00
3     pink   6023  #FFC0CB
4     gray   4087  #808080
5     none   3530  #E9E9E9
6   orange   2924  #FFA500
7    black   2355  #000000
8    green   1385  #00FF00
9      red   1013  #FF0000
10  purple   1012  #800080
11    buff    934  #F0DC82

In [15]:
stem_color_df = data['stem-color'].value_counts()
stem_color_df = pd.DataFrame(stem_color_df)
stem_color_df = stem_color_df.rename(columns={'stem-color': 'count'})
stem_color_df = stem_color_df.reset_index()
stem_color_df = stem_color_df.rename(columns={'index': 'value'})
stem_color_df['color'] = stem_color_df['value'].apply(lambda x: hexcode_func(x))
stem_color_df

     value  count    color
0    white  22943  #FFFFFF
1    brown  18079  #964B00
2   yellow   7788  #FFFF00
3     gray   2656  #808080
4   orange   2221  #FFA500
5      red   2039  #FF0000
6   purple   1488  #800080
7     none   1059  #E9E9E9
8     pink   1034  #FFC0CB
9    black    831  #000000
10   green    532  #00FF00
11    blue    239  #0000FF
12    buff    160  #F0DC82

In [16]:
has_ring_df = data['has-ring'].value_counts()
has_ring_df = pd.DataFrame(has_ring_df)
has_ring_df = has_ring_df.rename(columns={'has-ring': 'count'})
has_ring_df = has_ring_df.reset_index()
has_ring_df = has_ring_df.rename(columns={'index': 'value'})
has_ring_df['color'] = has_ring_df['value'].apply(lambda x: hexcode_func(x))
has_ring_df

   value  count    color
0  False  45890  #e6e6e6
1   True  15179  #666666

In [17]:
ring_type_df = data['ring-type'].value_counts()
ring_type_df = pd.DataFrame(ring_type_df)
ring_type_df = ring_type_df.rename(columns={'ring-type': 'count'})
ring_type_df = ring_type_df.reset_index()
ring_type_df = ring_type_df.rename(columns={'index': 'value'})
ring_type_df['color'] = ring_type_df['value'].apply(lambda x: hexcode_func(x))
ring_type_df

        value  count    color
0        none  50832  #E9E9E9
1  evanescent   2468  #66c1e5
2        zone   2118  #7ccae9
3     flaring   1425  #87ceeb
4       large   1404  #92d3ed
5     grooved   1239  #a8dcf0
6     pendant   1230  #bee5f4
7     movable    353  #d3edf8

In [18]:
habitat_df = data['habitat'].value_counts()
habitat_df = pd.DataFrame(habitat_df)
habitat_df = habitat_df.rename(columns={'habitat': 'count'})
habitat_df = habitat_df.reset_index()
habitat_df = habitat_df.rename(columns={'index': 'value'})
habitat_df['color'] = habitat_df['value'].apply(lambda x: hexcode_func(x))
habitat_df

     value  count    color
0    woods  44348  #f9d51f
1  grasses   7825  #fada38
2   leaves   3117  #fbde51
3  meadows   2972  #fbe36a
4   heaths   1963  #fce883
5    waste    353  #fcea8b
6    paths    350  #fcec9c
7    urban    141  #fdf1b4

In [19]:
season_df = data['season'].value_counts()
season_df = pd.DataFrame(season_df)
season_df = season_df.rename(columns={'season': 'count'})
season_df = season_df.reset_index()
season_df = season_df.rename(columns={'index': 'value'})
season_df['color'] = season_df['value'].apply(lambda x: hexcode_func(x))
season_df

    value  count    color
0  autumn  30150  #ff9900
1  summer  22857  #84B674
2  winter   5333  #99ccff
3  spring   2729  #03FF7F

In [20]:
class_df.to_csv('bar_chart_csv/class.csv', index=False)
cap_shape_df.to_csv('bar_chart_csv/cap_shape.csv', index=False)
cap_surface_df.to_csv('bar_chart_csv/cap_surface.csv', index=False)
cap_color_df.to_csv('bar_chart_csv/cap_color.csv', index=False)
bruise_bleed_df.to_csv('bar_chart_csv/bruise_bleed.csv', index=False)
gill_attachment_df.to_csv('bar_chart_csv/gill_attachment.csv', index=False)
gill_spacing_df.to_csv('bar_chart_csv/gill_spacing.csv', index=False)
gill_color_df.to_csv('bar_chart_csv/gill_color.csv', index=False)
stem_color_df.to_csv('bar_chart_csv/stem_color.csv', index=False)
has_ring_df.to_csv('bar_chart_csv/has_ring.csv', index=False)
ring_type_df.to_csv('bar_chart_csv/ring_type.csv', index=False)
habitat_df.to_csv('bar_chart_csv/habitat.csv', index=False)
season_df.to_csv('bar_chart_csv/season.csv', index=False)