In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('north_american_secondary_data_shuffled.csv', sep = ',')

In [3]:
# replace all letters with actual value

data = data.replace(
    {
    'class': {'[p]': 'poisonous', '[e]': 'edible'},
    'cap-shape': {'b': 'bell', 'c': 'conical', 'x': 'convex', 'f': 'flat', 's': 'sunken', 'p': 'spherical', 'o': 'others'},
    'cap-surface': {'i': 'fibrous', 'g': 'grooves', 'y': 'scaly', 's': 'smooth', 'd': 'dry', 'h': 'shiny', 'l': 'leathery', 'k': 'silky', 't': 'sticky', 'w': 'wrinkled', 'e': 'fleshy'},
    'cap-color': {'n': 'brown', 'b': 'buff', 'g': 'gray', 'r': 'green', 'p': 'pink', 'u': 'purple', 'e': 'red', 'w': 'white', 'y': 'yellow', 'l': 'blue', 'o': 'orange', 'k': 'black'},
    'gill-attachment': {'a': 'adnate', 'x': 'adnexed', 'd': 'decurrent', 'e': 'free', 's': 'sinuate', 'p': 'pores', 'f': 'none', '?': 'unknown'},
    'gill-spacing': {'c': 'close', 'd': 'distant', 'f': 'none'},
    'gill-color': {'n': 'brown', 'b': 'buff', 'g': 'gray', 'r': 'green', 'p': 'pink', 'u': 'purple', 'e': 'red', 'w': 'white', 'y': 'yellow', 'l': 'blue', 'o': 'orange', 'k': 'black', 'f': 'none'},
    'stem-color': {'n': 'brown', 'b': 'buff', 'g': 'gray', 'r': 'green', 'p': 'pink', 'u': 'purple', 'e': 'red', 'w': 'white', 'y': 'yellow', 'l': 'blue', 'o': 'orange', 'k': 'black', 'f': 'none'},
    'ring-type': {'c': 'cobwebby', 'e': 'evanescent', 'r': 'flaring', 'g': 'grooved', 'l': 'large', 'p': 'pendant', 's': 'sheathing', 'z': 'zone', 'y': 'scaly', 'm': 'movable', 'f': 'none', '?': 'unknown'},
    'habitat': {'g': 'grasses', 'l': 'leaves', 'm': 'meadows', 'p': 'paths', 'h': 'heaths', 'u': 'urban', 'w': 'waste', 'd': 'woods'},
    'season': {'s': 'spring', 'u': 'summer', 'a': 'autumn', 'w': 'winter'}
    })

# convert t/f columns to boolean.
data['does-bruise-or-bleed'] = data['does-bruise-or-bleed']=='t'
data['has-ring'] = data['has-ring']=='t'

In [4]:
data

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,edible,6.86,flat,scaly,brown,False,free,close,white,13.68,...,NaN,NaN,white,NaN,NaN,False,none,NaN,woods,summer
1,edible,5.41,convex,dry,brown,False,adnate,close,brown,7.87,...,NaN,NaN,brown,NaN,NaN,True,evanescent,NaN,woods,spring
2,poisonous,5.25,convex,smooth,yellow,True,sinuate,close,buff,3.91,...,NaN,NaN,red,NaN,NaN,False,none,NaN,woods,summer
3,edible,10.90,conical,sticky,orange,False,free,close,yellow,12.78,...,NaN,NaN,yellow,NaN,NaN,True,flaring,NaN,woods,summer
4,poisonous,12.80,convex,sticky,brown,True,decurrent,close,white,5.98,...,NaN,NaN,brown,NaN,NaN,False,none,NaN,woods,autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34589,edible,2.25,flat,smooth,brown,True,decurrent,distant,buff,13.56,...,NaN,NaN,brown,NaN,NaN,False,none,NaN,woods,autumn
34590,edible,4.36,flat,smooth,pink,False,none,none,none,3.28,...,NaN,NaN,red,NaN,NaN,False,none,NaN,woods,autumn
34591,poisonous,4.94,convex,silky,white,False,adnate,distant,buff,4.76,...,NaN,NaN,buff,NaN,NaN,False,none,NaN,woods,winter
34592,edible,3.79,convex,sticky,yellow,False,decurrent,distant,white,4.90,...,NaN,NaN,yellow,NaN,NaN,False,none,NaN,woods,summer
34593,edible,0.71,sunken,dry,yellow,False,none,none,none,2.52,...,NaN,NaN,orange,NaN,NaN,False,none,NaN,woods,summer

In [5]:
data.drop(columns=['stem-root', 'stem-surface', 'veil-type', 'veil-color', 'spore-print-color'], inplace=True)
data

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
0,edible,6.86,flat,scaly,brown,False,free,close,white,13.68,15.85,white,False,none,woods,summer
1,edible,5.41,convex,dry,brown,False,adnate,close,brown,7.87,7.05,brown,True,evanescent,woods,spring
2,poisonous,5.25,convex,smooth,yellow,True,sinuate,close,buff,3.91,12.07,red,False,none,woods,summer
3,edible,10.90,conical,sticky,orange,False,free,close,yellow,12.78,14.53,yellow,True,flaring,woods,summer
4,poisonous,12.80,convex,sticky,brown,True,decurrent,close,white,5.98,18.45,brown,False,none,woods,autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34589,edible,2.25,flat,smooth,brown,True,decurrent,distant,buff,13.56,9.96,brown,False,none,woods,autumn
34590,edible,4.36,flat,smooth,pink,False,none,none,none,3.28,15.25,red,False,none,woods,autumn
34591,poisonous,4.94,convex,silky,white,False,adnate,distant,buff,4.76,8.84,buff,False,none,woods,winter
34592,edible,3.79,convex,sticky,yellow,False,decurrent,distant,white,4.90,14.65,yellow,False,none,woods,summer
34593,edible,0.71,sunken,dry,yellow,False,none,none,none,2.52,3.36,orange,False,none,woods,summer

In [6]:
class_df = data["class"].value_counts()
class_df = pd.DataFrame(class_df)
class_df

           class
poisonous  18356
edible     16238

In [7]:
cap_shape_df = data["cap-shape"].value_counts()
cap_shape_df = pd.DataFrame(cap_shape_df)
cap_shape_df

           cap-shape
convex         19874
flat            8657
sunken          2436
conical         1116
bell            1042
others           983
spherical        486

In [8]:
cap_surface_df = data["cap-surface"].value_counts()
cap_surface_df = pd.DataFrame(cap_surface_df)
cap_surface_df

          cap-surface
smooth           9213
dry              7440
sticky           6863
scaly            4112
grooves          1738
fibrous          1625
silky             869
fleshy            846
shiny             714
wrinkled          706
leathery          305
de                163

In [9]:
cap_color_df = data["cap-color"].value_counts()
cap_color_df = pd.DataFrame(cap_color_df)
cap_color_df

        cap-color
brown        8524
white        5458
yellow       4429
red          3711
orange       3614
buff         2775
gray         2028
pink         1453
purple       1069
green         820
black         630
blue           83

In [10]:
bruise_bleed_df = data["does-bruise-or-bleed"].value_counts()
bruise_bleed_df = pd.DataFrame(bruise_bleed_df)
bruise_bleed_df

       does-bruise-or-bleed
False                 21180
True                  13414

In [11]:
gill_attachment_df = data["gill-attachment"].value_counts()
gill_attachment_df = pd.DataFrame(gill_attachment_df)
gill_attachment_df

           gill-attachment
adnate                9582
decurrent             8239
free                  6880
pores                 4236
adnexed               2643
sinuate               1602
none                  1412

In [12]:
gill_spacing_df = data["gill-spacing"].value_counts()
gill_spacing_df = pd.DataFrame(gill_spacing_df)
gill_spacing_df

         gill-spacing
close           23831
none             5648
distant          5115

In [13]:
gill_color_df = data["gill-color"].value_counts()
gill_color_df = pd.DataFrame(gill_color_df)
gill_color_df

        gill-color
white        13302
none          5648
yellow        3505
pink          3209
brown         2395
buff          1900
orange        1704
gray          1205
red            958
black          434
purple         224
green          110

In [14]:
stem_color_df = data["stem-color"].value_counts()
stem_color_df = pd.DataFrame(stem_color_df)
stem_color_df

        stem-color
white        14428
yellow        5267
brown         4041
orange        3281
buff          2174
red           1859
gray          1198
pink          1186
purple         418
green          353
none           157
black          121
blue           111

In [15]:
has_ring_df = data["has-ring"].value_counts()
has_ring_df = pd.DataFrame(has_ring_df)
has_ring_df

       has-ring
False     26828
True       7766

In [16]:
ring_type_df = data["ring-type"].value_counts()
ring_type_df = pd.DataFrame(ring_type_df)
ring_type_df

            ring-type
none            26828
flaring          2943
evanescent       2649
grooved           696
zone              645
large             464
pendant           188
movable           181

In [17]:
habitat_df = data["habitat"].value_counts()
habitat_df = pd.DataFrame(habitat_df)
habitat_df

         habitat
woods      30114
grasses     1971
urban        632
meadows      528
leaves       517
paths        368
heaths       360
waste        104

In [18]:
season_df = data["season"].value_counts()
season_df = pd.DataFrame(season_df)
season_df

        season
autumn   15815
summer   14502
spring    3932
winter     345

In [ ]:
encoded_data = pd.get_dummies(data=data, columns=[
                                                'cap-surface',
                                                'cap-color',
                                                'does-bruise-or-bleed',
                                                'gill-attachment',
                                                'gill-spacing',
                                                'gill-color',
                                                'cap-shape',
                                                'stem-color',
                                                'has-ring',
                                                'ring-type',
                                                'habitat',
                                                'season'])
encoded_data

In [ ]:
from sklearn.preprocessing import LabelEncoder
  
le = LabelEncoder()
encoded_data['class']= le.fit_transform(encoded_data['class'])

In [ ]:
encoded_data

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
target = encoded_data["class"]
target_names = ["edible", "poisonous"]

In [ ]:
na_mushroom_df = encoded_data.drop("class", axis=1)
feature_names = na_mushroom_df.columns
na_mushroom_df.head()